"""add emotion to messages

Revision ID: 84cedba7a50a
Revises: 0c4e9daba6cf
Create Date: 2026-05-04 15:52:41.126332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84cedba7a50a'
down_revision: Union[str, None] = '0c4e9daba6cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('emotion', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'emotion')
    # ### end Alembic commands ###
